### PR TITLE
Add getNearestTile function that gets nearest tile to local player

### PR DESCRIPTION
**Pull request by dginovker**

### CODE REVIEW

**Review by GigiaJ — CHANGES_REQUESTED** [review]
No. Do not get this in the wrapper classes. 
This can be instead performed in the Player class.

**Comment by dginovker** [comment]
But I want to do `area.getNearestTile()`, not `player.getNearestTile(area)`

Lots of bot APIs (Dreambot, the old Exobot, I think even Osbot) have this. It's very nice for the scripter

**Comment by GigiaJ** [comment]
When I make changes that allow instances of bots to be run using shared resources this will break though. While right now it doesn't support it, I do plan to re-add the functionality. (Currently, I'll need to look into working around the GUI limitations, but it should be doable.) It'll make the API more scaleable than launching individual JVM instances *per* bot.

**Comment by GigiaJ** [comment]
I should add before I swapped to RuneLite's GUI usage (it had its own GUI prior) the API did fully support this and no radical changes have been made to break that.

**Comment by dginovker** [comment]
That's really cool. Awesome to know, will close 😄

**Pull request closed without merging**
