### PR TITLE
ScriptPanel UI upgrade to PNG Icons

### PR DESCRIPTION
**Pull request by myzsqn**
- Upgrade to a "toolbar" of icons to control scripts instead of plain…
- Disable "Start Script" by default, it will enable once a script is selected

image

### CODE REVIEW

**Review by dginovker — APPROVED** [review]
Brilliant idea, without checking out the branch though do the MaterialTabs have any feedback when pressed? I.e. JButtons move down a bit on pressed so you know it's been triggered

**Comment by myzsqn** [comment]
So, I've seen other plugins use something like this: 

```
                        tab.setOnSelectEvent(() ->
			{
                               //wonderful logic
				return true;
			});

			tab.addMouseListener(new MouseAdapter()
			{
				@Override
				public void mousePressed(MouseEvent mouseEvent)
				{
					if (loading)
					{
						return;
					}

					lookup();
				}
			});
```

I haven't figured out why other plugins use the OnSelectEvent, I was having issues with it functioning... It seems using the mousePressed as the trigger is more reliable

**Comment by myzsqn** [comment]
But, sorry there isn't any "feedback" persay, I misunderstood you at first

**Comment by GigiaJ** [comment]
Neat. Not sure why OnSelectedEvent isn't working since those *are* tabs, but oh well.

**Review by GigiaJ — APPROVED** [review]

**Pull request merged**
